### ISSUE TITLE
Externally edited file with syntax issue gets silently deleted

### ISSUE THREAD

**Issue by eMPee584** [mdSilo/mdSilo-app#560] opened 2023-10-16 10:36 UTC
I'm just starting to move my workflow of storing learnings in telegram saved messages stream to mdSilo. So I put a `<code>` snippet in a bullet list and wanted to get rid of the empty line at the start (same issue with YT videos in bullet lists):
![mdSilo-formatting-issue](https://github.com/mdSilo/mdSilo-app/assets/1227833/3a3dc55a-dd71-4463-b623-f470ea33e90b)
But wasn't able from within the interface. I then fired up `vim`, removed the line break and spaces to match up the tick³, saved - and the file was gone. It's reproducable, seems mdSilo eats any file it doesn't like the syntax of.. this is my test case `terminal-tricks.md` file:

```
### ripgrep
- ```
         -p, --pretty
             This is a convenience alias for --color always --heading --line-number.
             This flag is useful when you still want pretty output even if you’re
             piping ripgrep to another program or file. For example: rg -p foo | less
             -R.
``` # comment because of nested code block, remove
```
This is mdSilo 0.5.7 on debian unstable.

- [x] I'm willing to submit a PR!

**Comment by danloh** [comment] 2024-01-27 18:23
Actually, I tried but cannot reproduced the issue. I will continue to try.

**Comment by danloh** [comment] 2024-02-25 19:13
I still cannot reproduce. I am closing this, feel free to reopen it with more details. Thanks.

**Closed by danloh** 2024-02-25 19:13 UTC
Labels: bug
